#!/bin/bash

if [-d ./bin]; then
  echo "Changing to bin directory"
  cd ./bin
else
  echo "Making a bin output directory"
  mkdir ./bin
  echo "Changing to bin directory"
  cd ./bin
fi
cmake ..
make
